### ISSUE TITLE
Difference between this and ThreeTenABP?

### ISSUE THREAD

**Issue by tsuharesu** [gabrielittner/lazythreetenbp#18]
What would be the difference in using this with `no-tzdb` or using https://github.com/JakeWharton/ThreeTenABP?

**Comment by gabrielittner** [comment]
ThreeTenABP also depends on the `no-tzdb` variant of threetenbp: https://github.com/JakeWharton/ThreeTenABP/blob/master/threetenabp/build.gradle#L4

The difference between the two libraries is what happens you call their init methods. `AndroidThreeTen.init(this)` will register it's time zone provider and load all time zones immediately from the bundled time zone database. Calling `LazyThreeTen.init(this)` will only do the registration. It will only load time zones from the database when they are accessed and then it will only load that specific time zone instead of all.

**Comment by ghost** [comment]
This no longer true I believe after this change:
https://github.com/JakeWharton/ThreeTenABP/commit/fd0863ea5f0e75b0262cbad76d69d1356fa9a236

I also did a test on a Pixel phone, both took around 1~2 ms
